### ISSUE TITLE
Add Input Validation

### ISSUE THREAD

**Issue by davemachado** [davemachado/Finance-Planner#23]
Need to add input validation for restricting user input to safe values.

**Comment by davemachado** [comment]
Should this be implemented per feature, or include in utility engine? If engine, would we need to offer different types of validation to cover all features? (is a range of values valid, are only certain specific values valid, etc).

**Comment by OnlyLAGcanSTOPme** [comment]
It's possible we might have more validation to do in the future so let's keep one per feature. But thank you for bring this up. :)

**Comment by davemachado** [comment]
Agreed, thanks for triaging with me, Sungsoo!
