### ISSUE TITLE
Eclipse won't create new JAVA files

### ISSUE THREAD

**Issue by davemachado** [davemachado/Finance-Planner#27]
Original Question (7/3/2016 8:14pm):

> ok so I was able to pull the files from GitHub successfully to set up the
> (general) project in Eclipse but when I try to create a java file it says
> this is not java project so you can't create one. Have you had this kind
> issue?
> 
> Thanks

**Comment by davemachado** [comment]
I can't add too much value here, but maybe @DanielDiTommaso has run into this during his Eclipse work over the past few months.

**Comment by davemachado** [comment]
@OnlyLAGcanSTOPme any update on this? Has Eclipse started behaving yet?

**Comment by OnlyLAGcanSTOPme** [comment]
Not yet, I'm working on it. But for now I'll create a new file on Github directly.

**Comment by davemachado** [comment]
You could also try just working with the Git GUI of your choice (SourceTree, GItKraken, etc), editing files in a text editor and using terminal/cmd to compile.

**Comment by ron12013** [comment]
Maybe you need to place your cloned repository folder in your work space in order to make it work in eclipse, I am not sure though

**Comment by OnlyLAGcanSTOPme** [comment]
Solved! Thanks
