### ISSUE TITLE
Update on Sprint 1.0

### ISSUE THREAD

**Issue by davemachado** [davemachado/Finance-Planner#30]
@OnlyLAGcanSTOPme , can you please update on your status from the last sprint and what you plan to do for the second sprint? Thank you.

**Comment by OnlyLAGcanSTOPme** [comment]
Hi Dave, I did pull-request for a new file I created for Add-User function.
i want to make sure I did it correctly

**Comment by davemachado** [comment]
Hi Sungsoo, 

It looks like the pull request did not work as expected, since it is not showing up on the PR page. Did you set the base to be this repo and not your fork?

**Comment by OnlyLAGcanSTOPme** [comment]
i did it last night. But I noticed no one has reviewed it yet

**Comment by davemachado** [comment]
Can you add a link to it here? It's not showing up on the pull requests page for this repo.

**Comment by OnlyLAGcanSTOPme** [comment]
Ok now I think I got it.
I went to
davemachado <https://github.com/davemachado>/Finance-Planner
<https://github.com/davemachado/Finance-Planner> and compare across folks

base fork: davemachado <https://github.com/davemachado>/Finance-Planner
<https://github.com/davemachado/Finance-Planner> base: developer head fork:
mine compare: my new branch

would this be correct?

**Comment by davemachado** [comment]
you need to set the base as davemachado(owner)/Finance-Planner. Otherwise the PR won't be set up correctly. At this time it still is not set up. Here is a video that should help:

https://www.youtube.com/watch?v=YTbRzhQju4c

**Comment by davemachado** [comment]
@DanielDiTommaso and @ron12013 might also find this video helpful.
https://www.youtube.com/watch?v=YTbRzhQju4c
